/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package io.zdp.wallet.desktop.ui.gui.dialog;

/**
 *
 * @author Sergey
 */
public class MyAddressesPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyAddressesPanel
     */
    public MyAddressesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        html = new javax.swing.JEditorPane();
        btnAddExistingAddress = new javax.swing.JButton();
        btnGenerateNewAddress = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        html.setEditable(false);
        html.setContentType("text/html"); // NOI18N
        html.setText("<html style=\"background:black;color:white;\">\n\t<head style=\"background:black;color:white;\">\n\n\t</head>\n\t<body>\n\t<h1>There are no addresses in this wallet</h1>\n\t</body>\n</html>\n");
        jScrollPane1.setViewportView(html);

        btnAddExistingAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_24.png"))); // NOI18N
        btnAddExistingAddress.setText("Add existing address by secret number");

        btnGenerateNewAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_24.png"))); // NOI18N
        btnGenerateNewAddress.setText("Generate new address");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html> <h1>My addresses</h1> </html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddExistingAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                        .addComponent(btnGenerateNewAddress))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddExistingAddress)
                    .addComponent(btnGenerateNewAddress))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddExistingAddress;
    public javax.swing.JButton btnGenerateNewAddress;
    public javax.swing.JEditorPane html;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
