/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package io.zdp.wallet.desktop.ui.gui.dialog;

/**
 *
 * @author Sergey
 */
public class ReceivePanel extends javax.swing.JPanel {

    /**
     * Creates new form ReceivePanel
     */
    public ReceivePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        html = new javax.swing.JEditorPane();
        linkAddressBook = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html> <h1>Receive</h1> </html>");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select an address below and give it to the sender:");

        html.setEditable(false);
        html.setContentType("text/html"); // NOI18N
        html.setText("<html style=\"background:black;color:white;\">\n\t<head style=\"background:black;color:white;\">\n\n\t</head>\n\t<body>\n\t\t<div style=\"margin-top: 0;background:white;color:black;padding:10px 10px 10px 10px;border-radius:6px;\">\n\t\t\t<table width=\"100%\" border='0'>\n\t\t\t\t<tr>\n\t\t\t\t\t<td>\n\t\t\t\t\t\n\t\t\t\t\t\t<div style='background:black;color:white;font-size:14px;padding:10px 10px 10px 10px;'>EWmjcBQCAa47AMknc5ks8rg2T5pyYNrHVjGv4VQ868Tj</div>\n\t\t\t\t\t\t\n\t\t\t\t\t\t<br/>\n\t\t\t\t\t\t\n\t\t\t\t\t\t<div style='padding-top:5px'>\n\t\t\t\t\t\t\tThis a temporary address that I used to send funds too (max 256 characters)\n\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\n\t\t\t\t\t\t<br>\n\t\t\t\t\t\t<div>Balance: <b>143.23223</b></div>\n\t\t\t\t\t</td>\n\n\t\t\t\t\t<td width=\"128\" align=\"center\">\n\t\t\t\t\t\t<img src=\"http://api.zdp.io/api/address/qr/160/92qphxD7HsuXfNpSpBXPt2jTwTHaGSB7XVJtLDdsHA1j.jpg\" />\n\t\t\t\t\t</td>\n\t\t\t\t</tr>\n\n\n\t\t\t</table>\n\n\t\t</div>\n\t</body>\n</html>\n");
        jScrollPane1.setViewportView(html);

        linkAddressBook.setForeground(new java.awt.Color(0, 102, 255));
        linkAddressBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linkAddressBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info_32.png"))); // NOI18N
        linkAddressBook.setText("<html><u>If you want to add a new address, please go to \"Address Book\"</u></html>");
        linkAddressBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(linkAddressBook))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkAddressBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JEditorPane html;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel linkAddressBook;
    // End of variables declaration//GEN-END:variables
}
